spring:
  application:
    name: cn.edu.neu.zy.provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 160039
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: provider6
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.neu.zy.provider.bean


info.app.name: cn.edu.neu.zy.provider
info.company.name: neu
info.author.name: zy
logging:
  level:
    root: INFO